join_message: '&8[&aIZ&8] &7%player%'
leave_message: '&8[&cIZ&8] &7%player%'
chat_format: '%player% -> %message%'
commandspy:
  filters:
    default:
    - 'c give'
    - 'c i'
    - 'c item'
    all:
    - '*'
  players:
    bobmandude9889:
      filter: default
colors:
  - 'Visitor,7'
  - 'Member,a'
  - 'MemberP,2'
  - 'Trusted,b'
  - 'Mod,c'
  - 'Admin,4'
  
ranks:
  - "&7Visitor"
  - "&aMember"
  - "&a&lMember Plus"
  - "&bTrusted"
  - "&9Mod"
  - "&cAdmin"
  - "&4Owner"

inventory_interact_worlds:
  - "spawn"
  
player_list_message: "&8&m-----------------&f☆&4&liZenith&f&lPVP&f☆&8&m-----------------\n&4&lSERVER IS STILL IN DEVELOPMENT.\n&4&lPLEASE REPORT ANY ISSUES USING /report <message>\n&7Online Players:"
  
tab:
  header: "&4&liZenith&f&lPVP\n&f  &7&m-----------------\n&4&lDonate: &f&lstore.izenith.net\n&4&lTeamSpeak: &f&ltalk.izenith.net\n\n&7Online: &c{ONLINE_PLAYERS}\n&7&m-----------------"
  footer: "&7&m-----------------\n\n&7Ping: {PING}\n&7K/D: &a{KILLS}&7/&c{DEATHS}&7 = &b{KD}\n&7Balance: &a${BALANCE}"
  
  
spawn_world: "spawn"
pvp_world: "kitpvp"

kit_title: "\u2606&4iZenith&8Kits\u2606"

block_conv:
    1,4: 35,0
    1,3: 42,0