name: IZenith
version: 1.0
main: net.izenith.Main.Main
author: bobmandude9889
depend: [Multiverse-Core,PermissionsEx,Vault,Essentials,Factions]

commands:
  commandspy:
    description: Commandspy
    usage: /<command>
    aliases: ['commandpsy','cs']
  report:
    description: Used to report problems
    usage: /<command>
  ranks:
    description: List servers ranks
    usage: /<command>
  ip:
    description: Shows the server's Ip Address
    usage: /<command>
  donated:
    description: Player donated
    usage: /<command>
  playtime:
    description: Get the time the player has played.
    usage: /<command> <player>
    aliases: [play,givemearimjobandbitemyear]
  updatelist:
    description: Update the tab list
    usage: /<command>
  adminchat:
    description: Send message or toggle
    usage: /<command>
    aliases: [ac]
  clearchat:
    description: Clear the server chat
    usage: /<command>
    aliases: [cc]
  rename:
    description: Renames item in hand
    usage: /<command> <name>
    aliases: [re]
  ping:
    description: Show the ping in milliseconds
    usage: /<command>
  ghost:
    description:
    usage: /<command>
  setkit:
    description: Create a kit for kit pvp
    usage: /<command> <name>
  kit:
    description: Get a kit by name
    usage: /<command> <name>
    aliases: [kits]
  rkits:
    decsription: Reload kits
    usage: /<command>
  clearkit:
    description: Clear Kit
    usage: /<command>
    aliases: [ckit]
  rankbuy:
    description: Used only by console
    usage: /<command>
  party:
    description: Party commands
    usage: /<command> <invite,kick,join,leave,list,help> [player]
  kd:
    description: View kds
    usage: /<command> <player,page>
  sell:
    decsription: Sell items
    usage: /<command>
  buy:
    description: Buy items
    usage: /<command>
    aliases: [shop]
  anvil:
    description: anvil
    usage: /<command>
  izreload:
    description: reload izenith
    usage: /<command>
   
permissions:
  commandspy.use:
    description: gives access to /commandspy
    default: OP
  clock.create:
    description: Gives access to /createclo
    default: OP
  setfloor.others:
    description: Set other player plot floor
    default: OP
  kit.use:
    description: Use Kits
    default: OP
  gkit.use:
    description: Create and remove Global Kits
    default: OP
  hub.suspend:
    description: Suspend players
    default: OP
  hub.cc:
    description: Clear Chats
    default: OP
  report.admin:
    description: gives access to /report list and remove
    default: OP
  izenith.adminchat:
    description: Can talk in admin chat
    default: OP
  izenith.updatelist:
    description: Gives /updatelist
    default: OP
  izenith.console:
    description: Gives /console
    default: OP
  bow.dick:
    description: Allows bow penis
    default: OP
  console.remoteaccess:
    description: Allows access to a key used for remote access
  izenith.rename:
    description: Renames the item in hand
    default: OP
  spawn.interact:
    description: Allows inventory interaction at spawn
    default: OP
  plot.rskull:
    description: Allows refreshing of plot skulls
    default: OP
  kit.create:
    description: Create a kit
    default: OP
  kit.reload:
    description: Reload kits
    default: OP
  kit.bypass_cooldown:
    description: Bypass cooldown
    default: OP
  iz.reload:
    description: Reload the izenith plugin
    default: OP