chat:
  Visitor: '%player% -> %message%'
  Member: '%player% -> %message%'
  Mod: '%player% -> &b%message%'
  Admin: '%player% -> &b%message%'
  Owner: '%player% -> &b%message%'
  
commandspy:
  filters:
    default:
    - 'c give'
    - 'c i'
    - 'c item'
    all:
    - '*'
  players:
    bobmandude9889:
      filter: default